name: 'datawarehouse'
version: '1.0.0'

profile: 'datawarehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  is_incremental_run: false

models:
  datawarehouse:

    staging:
      financial:
        +materialized: view
        +tags: ["staging"]

    marts:
      financial:
        dimensions:
          +materialized: table
          +tags: ["dimension"]

        facts:
          +materialized: table
          +tags: ["fact"]
