datawarehouse:
  outputs:
    dev:
      dbname: icatu_db
      host: "{{ env_var('POSTGRES_HOST') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 1
      type: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
  target: dev